#!/bin/sh
if [ "x$D" != "x" ]; then
	install -d $D/home/goembed/ti-sdk-am335x-evm-06.00.00.00/linux-devkit/sysroots/i686-arago-linux/etc/rcS.d
	# this happens at S98 where our good 'ole packages script used to run
	echo "#!/bin/sh
opkg-cl configure
rm -f //home/goembed/ti-sdk-am335x-evm-06.00.00.00/linux-devkit/sysroots/i686-arago-linux/etc/rcS.d/S98run-postinsts
" > $D/home/goembed/ti-sdk-am335x-evm-06.00.00.00/linux-devkit/sysroots/i686-arago-linux/etc/rcS.d/S98run-postinsts
	chmod 0755 $D/home/goembed/ti-sdk-am335x-evm-06.00.00.00/linux-devkit/sysroots/i686-arago-linux/etc/rcS.d/S98run-postinsts
fi
	update-alternatives --install /home/goembed/ti-sdk-am335x-evm-06.00.00.00/linux-devkit/sysroots/i686-arago-linux/usr/bin/opkg opkg opkg-cl 100
